In [3]:
import torch

sentence = torch.tensor(
    [0, # can
     7, # you     
     1, # help
     2, # me
     5, # to
     6, # translate
     4, # this
     3] # sentence
)
sentence

tensor([0, 7, 1, 2, 5, 6, 4, 3])

In [7]:
torch.manual_seed(1)

# 8 + reserved, 16: the double of 8
embed = torch.nn.Embedding(10, 16)
embedded_sentence = embed(sentence).detach()
embedded_sentence.shape

torch.Size([8, 16])

In [9]:
# compute the dot produot of w: omega_mat
omega = embedded_sentence.matmul(embedded_sentence.T)

In [13]:
# compute de attention weigths
import torch.nn.functional as F
attention_weights = F.softmax(omega, dim=1)
attention_weights.shape

torch.Size([8, 8])

In [20]:
attention_weights.sum(dim=1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])

In [24]:
context_vectors = torch.matmul(attention_weights, embedded_sentence)
context_vectors.shape

torch.Size([8, 16])

In [33]:
# query, key and value terminology

torch.manual_seed(1)
d = embedded_sentence.shape[1]
U_query = torch.rand(d, d)
U_key = torch.rand(d, d)
U_value = torch.rand(d, d)


In [44]:
# query projection matrix on x_2
x_2 = embedded_sentence[1]
query_2 = U_value.matmul(x_2)
query_2.shape

torch.Size([16])

In [45]:
keys = U_key.matmul(embedded_sentence.T).T
keys[0].shape


torch.Size([16])

In [48]:
omega_23 = query_2.dot(keys[2])
omega_23

tensor(-129.5723)

In [51]:
omega_2 = query_2.matmul(keys.T)
omega_2

tensor([-231.0863,  176.4582, -129.5723,  112.2206,  -64.9247,  -41.0491,
        -172.6091,   27.7152])

In [56]:
import torch

sentence = torch.tensor(
    [0, # can
     7, # you     
     1, # help
     2, # me
     5, # to
     6, # translate
     4, # this
     3] # sentence
)

torch.manual_seed(123)

# 8 + reserved, 16: the double of 8
embed = torch.nn.Embedding(10, 16)
embedded_sentence = embed(sentence).detach()
embedded_sentence.shape

torch.Size([8, 16])

In [57]:
d = embedded_sentence.shape[1]
one_U_query = torch.rand(d, d)

h = 8
multihead_U_query = torch.rand(h, d, d)
multihead_U_key = torch.rand(h, d, d)
multihead_U_value = torch.rand(h, d, d)

In [59]:
x_2 = embedded_sentence[1]
multihead_query_2 = multihead_U_query.matmul(x_2)
multihead_query_2.shape

torch.Size([8, 16])

In [63]:
multihead_key_2 = multihead_U_key.matmul(x_2)
multihead_key_2[2]

tensor([-1.1364, -1.1204, -2.4430, -0.5982, -0.8292, -1.4401, -3.3822,  0.1315,
        -1.2749, -0.7113, -1.0477, -3.8960, -1.0681, -0.1607, -0.1208, -0.1486])